"""
report_generator.py
Renders scan results (single URL or batch) as a self-contained HTML
dashboard, plus a JSON export for programmatic use.
"""

import html
import json
from datetime import datetime, timezone

VERDICT_COLOR = {"Dangerous": "#e5484d", "Suspicious": "#f5a623", "Likely Safe": "#2fb670"}
SEVERITY_COLOR = {"critical": "#e5484d", "warning": "#f5a623", "info": "#4b8bf4"}


def _result_card(result):
    color = VERDICT_COLOR[result["verdict"]]
    ml_line = (f'<div class="score-line">ML model: {result["ml_score"]}% phishing probability</div>'
               if result["ml_score"] is not None else
               '<div class="score-line">ML model: not loaded (heuristics only)</div>')

    finding_rows = ""
    for f in result["findings"]:
        fc = SEVERITY_COLOR[f["severity"]]
        finding_rows += f"""
        <div class="finding">
          <span class="badge" style="background:{fc}">{f["severity"].upper()}</span>
          <div>
            <strong>{html.escape(f["title"])}</strong>
            <div class="detail">{html.escape(f["detail"])}</div>
          </div>
        </div>"""

    return f"""
    <div class="card">
      <div class="card-header">
        <div class="url-text">{html.escape(result["url"])}</div>
        <div class="verdict-pill" style="background:{color}">{result["verdict"]}</div>
      </div>
      <div class="risk-row">
        <div class="risk-bar-track">
          <div class="risk-bar-fill" style="width:{result["risk_score"]}%;background:{color}"></div>
        </div>
        <div class="risk-number">{result["risk_score"]}/100</div>
      </div>
      {ml_line}
      <div class="findings-list">{finding_rows}</div>
    </div>"""


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Phishing URL Threat Report</title>
<style>
  :root {{ --bg:#0f1115; --card:#171a21; --border:#262b36; --text:#e6e8ec; --muted:#8b93a3; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; font-family:'Segoe UI',Roboto,-apple-system,sans-serif; background:var(--bg); color:var(--text); padding:40px 24px; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  header h1 {{ margin: 0 0 4px; font-size: 26px; }}
  header .meta {{ color: var(--muted); font-size: 14px; margin-bottom: 28px; }}
  .summary-row {{ display:flex; gap:14px; margin-bottom: 28px; }}
  .summary-pill {{ flex:1; background: var(--card); border:1px solid var(--border); border-radius:10px; padding:16px; text-align:center; }}
  .summary-pill .num {{ font-size: 28px; font-weight: 700; }}
  .summary-pill .label {{ color: var(--muted); font-size: 12.5px; margin-top: 4px; }}
  .card {{ background: var(--card); border:1px solid var(--border); border-radius: 12px; padding: 20px; margin-bottom: 16px; }}
  .card-header {{ display:flex; justify-content: space-between; align-items:center; gap: 12px; margin-bottom: 14px; }}
  .url-text {{ font-size: 14px; word-break: break-all; color: var(--text); }}
  .verdict-pill {{ padding: 5px 12px; border-radius: 20px; font-size: 12.5px; font-weight: 700; color: #0f1115; white-space:nowrap; }}
  .risk-row {{ display:flex; align-items:center; gap: 12px; margin-bottom: 8px; }}
  .risk-bar-track {{ flex:1; height:10px; background:#232733; border-radius:6px; overflow:hidden; }}
  .risk-bar-fill {{ height:100%; border-radius:6px; }}
  .risk-number {{ width: 60px; text-align:right; font-weight:700; font-size: 13px; }}
  .score-line {{ color: var(--muted); font-size: 12.5px; margin-bottom: 12px; }}
  .findings-list {{ display:flex; flex-direction:column; gap:10px; margin-top: 10px; }}
  .finding {{ display:flex; gap:10px; align-items:flex-start; font-size: 13px; }}
  .badge {{ padding:3px 8px; border-radius:4px; font-size:10.5px; font-weight:700; color:#0f1115; white-space:nowrap; margin-top:1px; }}
  .detail {{ color: var(--muted); font-size: 12.5px; margin-top: 2px; }}
  footer {{ color: var(--muted); font-size: 12px; text-align: center; margin-top: 30px; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>Phishing URL Threat Report</h1>
    <div class="meta">generated {generated_at} &nbsp;\u2022&nbsp; {count} URL(s) scanned</div>
  </header>

  <div class="summary-row">
    <div class="summary-pill"><div class="num" style="color:{dangerous_color}">{dangerous_count}</div><div class="label">Dangerous</div></div>
    <div class="summary-pill"><div class="num" style="color:{suspicious_color}">{suspicious_count}</div><div class="label">Suspicious</div></div>
    <div class="summary-pill"><div class="num" style="color:{safe_color}">{safe_count}</div><div class="label">Likely Safe</div></div>
  </div>

  {cards}

  <footer>Generated by Phishing URL &amp; Threat Detector \u2014 ML + heuristic hybrid scanner.</footer>
</div>
</body>
</html>
"""


def generate_html(results, output_path):
    counts = {"Dangerous": 0, "Suspicious": 0, "Likely Safe": 0}
    for r in results:
        counts[r["verdict"]] += 1

    cards = "\n".join(_result_card(r) for r in results)

    html_out = HTML_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        count=len(results),
        dangerous_count=counts["Dangerous"],
        suspicious_count=counts["Suspicious"],
        safe_count=counts["Likely Safe"],
        dangerous_color=VERDICT_COLOR["Dangerous"],
        suspicious_color=VERDICT_COLOR["Suspicious"],
        safe_color=VERDICT_COLOR["Likely Safe"],
        cards=cards,
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_out)
    return output_path


def generate_json(results, output_path):
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "count": len(results),
        "results": results,
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    return output_path
